# Generated by Django 3.1.7 on 2021-03-31 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0001_initial'),
        ('reports', '0002_report_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMSEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('panel_antenna', 'панельная антенна'), ('RRL_antenna', 'РРЛ антенна'), ('radio_module', 'радиомодуль')], default='панельная антенна', max_length=20, verbose_name='Тип')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Высота')),
                ('proportions', models.IntegerField(blank=True, null=True, verbose_name='Размеры')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='Количество')),
                ('manufacturer', models.CharField(blank=True, max_length=50, verbose_name='Производитель')),
                ('model', models.CharField(blank=True, max_length=50, verbose_name='Модель')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='Примечание')),
                ('ams', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ams.ams', verbose_name='Объект / наряд')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ams.operator', verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'Оборудование на АМС',
                'verbose_name_plural': 'Оборудование на АМС',
            },
        ),
    ]
