# Generated by Django 3.1.7 on 2021-03-26 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AMSType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('code_alternative', models.CharField(max_length=50)),
                ('region_code', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('latitude', models.CharField(blank=True, max_length=50)),
                ('longitude', models.CharField(blank=True, max_length=50)),
                ('section_type', models.CharField(choices=[('square', 'Квадрат'), ('triangle', 'Треугольник'), ('circle', 'Круг')], default='Квадрат', max_length=8)),
                ('section_length', models.CharField(blank=True, max_length=50)),
                ('ferm_type', models.CharField(choices=[('sq_ferm', 'ферма квадратная'), ('tr_ferm', 'ферма треугольная'), ('pipe', 'труба'), ('pillar', 'столб')], default='ферма квадратная', max_length=7)),
                ('ams_height', models.CharField(blank=True, max_length=50)),
                ('signal_lights', models.BooleanField(default=True)),
                ('deviation', models.CharField(blank=True, max_length=50)),
                ('mounting_height', models.CharField(blank=True, max_length=50)),
                ('rope_diameter', models.CharField(blank=True, max_length=50)),
                ('ropes_amount', models.CharField(blank=True, max_length=50)),
                ('pulling', models.CharField(blank=True, max_length=50)),
                ('waterproofing', models.CharField(blank=True, max_length=50)),
                ('ams_manufacturer', models.CharField(blank=True, max_length=50)),
                ('ams_availability_operators', models.CharField(blank=True, max_length=50)),
                ('developer_project_documentation', models.CharField(blank=True, max_length=50)),
                ('ams_schema', models.ImageField(blank=True, upload_to='')),
                ('ams_layout_equipment_schema', models.ImageField(blank=True, upload_to='')),
                ('ams_photos', models.ImageField(blank=True, upload_to='')),
                ('ams_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ams.amstype')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ams.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ams.country')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ams.operator')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ams.region')),
            ],
        ),
    ]
